# https://github.com/cosmtrek/air/blob/master/air_example.toml

root = "."
testdata_dir = "test"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ."
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "test"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = true
  follow_symlink = true
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = 500 #ms
  log = "air.log"
  send_interrupt = false
  stop_on_error = true

[color]
  # Customize each part's color. If no color found, use the raw app log.
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  # Show log time
  time = true

[misc]
  # Delete tmp directory on exit
  clean_on_exit = trueZ

[screen]
  clear_on_rebuild = false
